### PR TITLE
mark ffi_service_main as public

### PR DESCRIPTION
**Pull request by ssrlive**
so we can use `ffi_service_main` from other module.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/127)

### CODE REVIEW

**Comment by pronebird** [comment]
Why would you want an implementation detail being public?

**Comment by ssrlive** [comment]
Here is my code. I call `ffi_service_main` from `bin` module.

`windows_service::service_dispatcher::start("dns-over-tls", dns_over_tls::ffi_service_main)?;`

image


> Why would you want an implementation detail being public?

**Comment by ssrlive** [comment]
I've changed it to pub(crate) so the function won't be accidentally exported. 
Anyway, this also adds a bit of flexibility to the user.

**Comment by faern** [comment]
This does not sound like something that should be exported by default. You can very easily re-export it yourself, so you are not blocked from implementing it in the way you want to anyway.

**Pull request closed without merging**
