### PR TITLE
Add service description

### PR DESCRIPTION
**Pull request by pronebird**
This PR is based off https://github.com/mullvad/windows-service-rs/pull/32 & adds the support for changing the service description along with minor refactoring & rustdoc fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @faern)

___
*[src/lib.rs, line 224 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKZcqP32MiJTpQSpXe4:-MKZcqP32MiJTpQSpXe5:b-tn1ooz) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/lib.rs#L224)):*
> ```Rust
>     InvalidStartArgument(#[error(source)] widestring::NulError<u16>),
> 
>     /// Invalid raw representation of [`ServiceState`](service::ServiceState).
> ```

FYI It looks like Rustdoc stopped picking up the references from the comments elsewhere in the document, so I used inline refs instead which worked.

```
$ cargo doc --open
warning: unresolved link to `ServiceStartType`
   --> src\lib.rs:231:40
    |
231 |     /// Invalid raw representation of [`ServiceStartType`].
    |                                        ^^^^^^^^^^^^^^^^^^ no item named `ServiceStartType` in scope
    |
    = note: `#[warn(broken_intra_doc_links)]` on by default
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `ServiceErrorControl`
   --> src\lib.rs:235:40
    |
235 |     /// Invalid raw representation of [`ServiceErrorControl`].
    |                                        ^^^^^^^^^^^^^^^^^^^^^ no item named `ServiceErrorControl` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `ServiceActionType`
   --> src\lib.rs:239:40
    |
239 |     /// Invalid raw representation of [`ServiceActionType`]
    |                                        ^^^^^^^^^^^^^^^^^^^ no item named `ServiceActionType` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: 3 warnings emitted
```

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-:-MKdMrE_05NRV6Kh9sXz:bnfp4nl)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @faern and @pronebird)

___
*[src/lib.rs, line 224 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKZcqP32MiJTpQSpXe4:-MKdN3DB60BfHLPtXzNU:b-ddxfm6) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/lib.rs#L224)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI It looks like Rustdoc stopped picking up the references from the comments elsewhere in the document, so I used inline refs instead which worked.

```
$ cargo doc --open
warning: unresolved link to `ServiceStartType`
   --> src\lib.rs:231:40
    |
231 |     /// Invalid raw representation of [`ServiceStartType`].
    |                                        ^^^^^^^^^^^^^^^^^^ no item named `ServiceStartType` in scope
    |
    = note: `#[warn(broken_intra_doc_links)]` on by default
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `ServiceErrorControl`
   --> src\lib.rs:235:40
    |
235 |     /// Invalid raw representation of [`ServiceErrorControl`].
    |                                        ^^^^^^^^^^^^^^^^^^^^^ no item named `ServiceErrorControl` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `ServiceActionType`
   --> src\lib.rs:239:40
    |
239 |     /// Invalid raw representation of [`ServiceActionType`]
    |                                        ^^^^^^^^^^^^^^^^^^^ no item named `ServiceActionType` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: 3 warnings emitted
```
</blockquote></details>

Rustdoc got smarter and smarter. Most of the time it should automatically pick up the link if you just do ```[`MyFooType`]``` in the documentation. Did you try that? :thinking: Maybe it won't work if the type is in a different module, not sure exactly how smart it is.
___
*[src/service.rs, line 154 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdNa2n1FMPAwGk1x1v:-MKdNa2n1FMPAwGk1x1w:b5k54l0) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L154)):*
> ```Rust
>     }
> 
>     pub fn from_system_identifier(identifier: impl AsRef<OsStr>) -> Self {
> ```

This is technically a breaking change*. So if you do this we would need to bump to `0.4.0`. That would not be optimal since we might want the segfault fixes from the other PR to be released as a patch release. We could release that one only as a patch release and this as `0.4.0`, but that does not sound optimal IMO.

In general I agree it's a nice change and we should move in this direction! :+1: but in itself only it's probably not worth a breaking release.

*: Iff anyone called this with `ServiceDependency::from_system_identifier::<SomeT>::(...)` then that would now give a compiler error since there is no generic parameter any more.
___
*[src/service.rs, line 1647 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdPwaI7vgEfkrVv4L0:-MKdPwaI7vgEfkrVv4L1:bcft8h5) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L1647)):*
> ```Rust
>         let wide_str =
>             WideCString::from_os_str(description).map_err(Error::InvalidServiceDescription)?;
>         let mut wide_str_vec = wide_str.into_vec_with_nul();
> ```

I don't think this `into_vec_with_nul()` is expensive. But I still think you can avoid it easily. There is an `as_ptr()` directly on `WideCString`. How about just `wide_str.as_ptr() as *mut _`? The mutability does not matter much here with the raw pointers anyway. It's defined as a `*mut` in the `SERVICE_DESCRIPTION` but I assume for all this method cares it's just going to read from it anyway?
___
*[src/service.rs, line 1651 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdPTvoEnbPVekashiV:-MKdPTvoEnbPVekashiW:b-48yl9g) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L1651)):*
> ```Rust
>         let mut service_description_request =
>             unsafe { mem::zeroed::<winsvc::SERVICE_DESCRIPTIONW>() };
>         service_description_request.lpDescription = wide_str_vec.as_mut_ptr();
> ```

Looks like you can avoid the unsafety altogether with something like:
```rust
let service_description = winsvc::SERVICE_DESCRIPTIONW {
    lpDescription: the_pointer,
};
```
Since it just has a single field, it's easy to initialize it by just specifying all fields.
___
*[src/service_manager.rs, line 39 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdQjkv4W2LSG8oCQMV:-MKdQjkw0Zfv_qvKNZqS:brbqm9p) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service_manager.rs#L39)):*
> ```Rust
>     ///   database.
>     fn new(
>         machine: Option<impl AsRef<OsStr>>,
> ```

Same as the threads above. Would be nice if we could release a non breaking change this time?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @pronebird)

___
*[src/lib.rs, line 224 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKZcqP32MiJTpQSpXe4:-MKdahcX4MUGaCUjyNdi:b-m2ck7w) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/lib.rs#L224)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Rustdoc got smarter and smarter. Most of the time it should automatically pick up the link if you just do ```[`MyFooType`]``` in the documentation. Did you try that? :thinking: Maybe it won't work if the type is in a different module, not sure exactly how smart it is.
</blockquote></details>

It doesn't work unless you specify the module or a reference. But references stopped working for some reason, maybe because we have refs in `//!` block which is somehow isolated from the rest of the document.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

___
*[src/service.rs, line 1647 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdPwaI7vgEfkrVv4L0:-MKdstuW0PmApjODNj8C:b-896fix) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L1647)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think this `into_vec_with_nul()` is expensive. But I still think you can avoid it easily. There is an `as_ptr()` directly on `WideCString`. How about just `wide_str.as_ptr() as *mut _`? The mutability does not matter much here with the raw pointers anyway. It's defined as a `*mut` in the `SERVICE_DESCRIPTION` but I assume for all this method cares it's just going to read from it anyway?
</blockquote></details>

Done.
___
*[src/service.rs, line 1651 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdPTvoEnbPVekashiV:-MKdsulR6TDeqy8N0uAB:b-896fix) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L1651)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Looks like you can avoid the unsafety altogether with something like:
```rust
let service_description = winsvc::SERVICE_DESCRIPTIONW {
    lpDescription: the_pointer,
};
```
Since it just has a single field, it's easy to initialize it by just specifying all fields.
</blockquote></details>

Done.
___
*[src/service_manager.rs, line 39 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdQjkv4W2LSG8oCQMV:-MKdsv_n-PYTiqaY1Ok0:b-896fix) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service_manager.rs#L39)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Same as the threads above. Would be nice if we could release a non breaking change this time?
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[src/service.rs, line 154 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-MKdNa2n1FMPAwGk1x1v:-MKdszUJ2pdhrs__AY34:b-896fix) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c0ddbf2a245716aa9f4538a49aa76e6deb5c402b/src/service.rs#L154)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is technically a breaking change*. So if you do this we would need to bump to `0.4.0`. That would not be optimal since we might want the segfault fixes from the other PR to be released as a patch release. We could release that one only as a patch release and this as `0.4.0`, but that does not sound optimal IMO.

In general I agree it's a nice change and we should move in this direction! :+1: but in itself only it's probably not worth a breaking release.

*: Iff anyone called this with `ServiceDependency::from_system_identifier::<SomeT>::(...)` then that would now give a compiler error since there is no generic parameter any more.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54#-:-MKdvGAb5zcUfLphOysZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
