### PR TITLE
Add service dependencies

### PR DESCRIPTION
**Pull request by pronebird**
This PR adds dependencies field support in `ServiceInfo`

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[src/service_manager.rs, line 252 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFqn4en6lvkxk2KmFC_:-LFqn4en6lvkxk2KmFCa:b-muhzj7) ([raw file](https://github.com/mullvad/windows-service-rs/blob/e775792ee75d0b9b9e5a9efd9cf909a5fb2b3247/src/service_manager.rs#L252)):*
> ```Rust
> 
> /// A helper to convert Vec<OsString> to double nul terminated WideString.
> /// Returns None if the source Vec is empty.
> ```

I personally don't know what "double nul terminated" means. Is this a well known concept? Could we maybe describe it a little bit more? If I understand the implementation correctly my summary would be something like:
"Concatenate a collection of `OsStr`s together with a `nul` delimiter in between"

---

*[src/service_manager.rs, line 254 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFqmw-l5Uh-_lsjroGr:-LFqmw-l5Uh-_lsjroGs:bktjsla) ([raw file](https://github.com/mullvad/windows-service-rs/blob/e775792ee75d0b9b9e5a9efd9cf909a5fb2b3247/src/service_manager.rs#L254)):*
> ```Rust
> /// Returns None if the source Vec is empty.
> fn to_double_nul_terminated<T: AsRef<OsStr>>(
>     source: Vec<T>,
> ```

Looks like you don't need ownership, could maybe take `source: &[T]`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 252 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFqn4en6lvkxk2KmFC_:-LFr1vN31sr-fQlfUV9s:bkz5bdc) ([raw file](https://github.com/mullvad/windows-service-rs/blob/e775792ee75d0b9b9e5a9efd9cf909a5fb2b3247/src/service_manager.rs#L252)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I personally don't know what "double nul terminated" means. Is this a well known concept? Could we maybe describe it a little bit more? If I understand the implementation correctly my summary would be something like:
"Concatenate a collection of `OsStr`s together with a `nul` delimiter in between"
</blockquote></details>

Since I actually mixed that up with `abc\0def\0` myself. I've expanded the documentation to help others get familiar with the quirks of WinAPI.

So to confirm, that function has to produce the nul-separated buffer ending with two nul bytes, for example the array of two elements should be represented as:

```
"abc\0def\0\0"
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 254 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFqmw-l5Uh-_lsjroGr:-LFr2JvI50FQbX85FLem:bctpdcc) ([raw file](https://github.com/mullvad/windows-service-rs/blob/e775792ee75d0b9b9e5a9efd9cf909a5fb2b3247/src/service_manager.rs#L254)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Looks like you don't need ownership, could maybe take `source: &[T]`?
</blockquote></details>

Makes sense. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-:-LFr42n3A816AqUOocFk:bnfp4nl)*

**Comment by faern** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[src/service_manager.rs, line 266 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr8XUZ8xgqq4BK_-Fs:-LFr8XUZ8xgqq4BK_-Ft:b-78c87s) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L266)):*
> ```Rust
>         for s in source {
>             let checked_str = WideCString::from_str(s)?;
>             wide.push_slice(checked_str.into_vec_with_nul());
> ```

The `into_vec_with_nul` here will cost an extra allocation just for the null byte. Would this not work:
```rust
wide.push_slice(checked_str.as_slice());
wide.push_slice(&[0u16]);
```
?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by faern** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[src/service_manager.rs, line 266 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr8XUZ8xgqq4BK_-Fs:-LFr91eC32uvoMbCSNL0:b-f3x6a7) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L266)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The `into_vec_with_nul` here will cost an extra allocation just for the null byte. Would this not work:
```rust
wide.push_slice(checked_str.as_slice());
wide.push_slice(&[0u16]);
```
?
</blockquote></details>

Or even better. We already have `impl AsRef<[u16]> for WideCString`. So just `wide.push_slice(checked_str)` would likely work as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[src/service_manager.rs, line 189 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr7-gZEiuOpGEMiS-c:-LFr9UsdBPADnHlPT6KU:b-68r9vx) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L189)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

pretty cool but that doesn't work for some reason now. I print the underlying Vec<u16> and it's correct, but then `WideString::as_ptr()` seems to be giving me busted pointer...
</blockquote></details>

@faern so here is the deal,

If I replace this line with:

```
joined_dependencies.as_ref().map_or(ptr::null(), |s| s.as_ptr()),
```

It works fine. I wonder, is it possible that doing `map` + `as_ptr()` in this fashion is actually unsafe because `map` will consume and drop the value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by faern** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 189 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr7-gZEiuOpGEMiS-c:-LFr9gki9kwmwTsoI2m9:b7oaeeg) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L189)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

@faern so here is the deal,

If I replace this line with:

```
joined_dependencies.as_ref().map_or(ptr::null(), |s| s.as_ptr()),
```

It works fine. I wonder, is it possible that doing `map` + `as_ptr()` in this fashion is actually unsafe because `map` will consume and drop the value.
</blockquote></details>

`map_or` consumes `self`. So the string would be dropped before your call to `CreateServiceW` indeed. I think that's the problem.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by faern** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 189 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr7-gZEiuOpGEMiS-c:-LFr9t3D-7pPzGbbkbRg:b-loc4k3) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L189)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`map_or` consumes `self`. So the string would be dropped before your call to `CreateServiceW` indeed. I think that's the problem.
</blockquote></details>

So doing `as_ref()` first would make you just borrow `joined_dependencies` and thus not drop it. So yeah, that is likely the case here. Great you found it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[src/service_manager.rs, line 266 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr8XUZ8xgqq4BK_-Fs:-LFrAaRo4QicJjBwzpJW:bdcv6kv) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L266)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Or even better. We already have `impl AsRef<[u16]> for WideCString`. So just `wide.push_slice(checked_str)` would likely work as well.
</blockquote></details>

Good point!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @faern)

---

*[src/service_manager.rs, line 266 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr8XUZ8xgqq4BK_-Fs:-LFrCYgC9W9LoiJvG_3i:b-896fix) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L266)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Good point!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 189 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr7-gZEiuOpGEMiS-c:-LFrCc4aEeVgKgewPBzY:b-zcg5xb) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L189)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

So doing `as_ref()` first would make you just borrow `joined_dependencies` and thus not drop it. So yeah, that is likely the case here. Great you found it.
</blockquote></details>

I applied the fix for `joined_dependencies` and `account_name` and `account_password`

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

---

*[src/service_manager.rs, line 189 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/6#-LFr7-gZEiuOpGEMiS-c:-LFrCyCLDF5JTttuZHQB:b-h7ys9a) ([raw file](https://github.com/mullvad/windows-service-rs/blob/796330bd4751f2202d3e2727db59f675d9091b26/src/service_manager.rs#L189)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I applied the fix for `joined_dependencies` and `account_name` and `account_password`
</blockquote></details>

Also just ran test and all of fields above are filled in properly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/6)*

**Pull request merged**
