### PR TITLE
Add support for user-defined control codes

### PR DESCRIPTION
**Pull request by vsrs**
Minor addition, no breaking changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/108)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/108#-:-Njgnoq_769DpAD6hTJf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @vsrs)

___
*[`src/service.rs` line 82 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/108#-NjgnKZcDHg9fCE6h7Q2:-NjgnKZcDHg9fCE6h7Q3:b-cptz7n) ([raw file](https://github.com/mullvad/windows-service-rs/blob/2f67a22c2ccfa22b51053b395e38a88a18e1e17b/src/service.rs#L82)):*
> ```XML
> 
>         /// Can use user-defined control codes
>         const NOTIFY = Services::SERVICE_USER_DEFINED_CONTROL;
> ```

Should we perhaps be consistent with the naming here? I.e., `USER_DEFINED_CONTROL` in this case.

**Review by vsrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/108)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`src/service.rs` line 82 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/108#-NjgnKZcDHg9fCE6h7Q2:-Njh35YE0HGAMRnONH-B:bujwkgy) ([raw file](https://github.com/mullvad/windows-service-rs/blob/2f67a22c2ccfa22b51053b395e38a88a18e1e17b/src/service.rs#L82)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we stick to naming these the same as the Windows constants? I.e., `USER_DEFINED_CONTROL` in this case.
</blockquote></details>

That makes sense, thank you. I've updated the code.

**Comment by vsrs** [comment]
@dlon, may you please complete the review? Thanks.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/108#-:-NjvepglDDMbI2yC6UFA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dlon** [comment]
Thanks.

**Pull request merged**
