### PR TITLE
Prepare to release 0.7.0

### PR DESCRIPTION
**Pull request by faern**
Lots of stuff has happened and a full year has passed since 0.6.0. It's about time we get with the times. Here I prepare for releasing 0.7.0. It's a breaking release because we upgrade `windows-sys`

I want #124 merged before we go ahead with this release.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/125)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/125#-:-NvI2iEECJkCLQdnuSWZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/125)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`CHANGELOG.md` line 23 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/125#-Nv_s5H81k98Zhvar4s_:-Nv_s5H81k98Zhvar4sa:b-6b2xqx) ([raw file](https://github.com/mullvad/windows-service-rs/blob/04c0b0c9ccd41404c92bc4e3de1e1e47e0a22ba1/CHANGELOG.md#L23)):*
> ```Markdown
> ### Changed
> - Breaking: Make a bunch of enums `#[non_exhaustive]`: `Error`, `PowerBroadcastSetting`,
>   `PowerEventParam`, `SessionChangeReason` and `ServiceControl`.
> ```

`SessionChangeReason` should be removed from here.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/125)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`CHANGELOG.md` line 23 at r2](https://reviewable.io/reviews/mullvad/windows-service-rs/125#-Nv_s5H81k98Zhvar4s_:-Nv_u3Ze1BZ5Yw3afN8o:b-33j7hy) ([raw file](https://github.com/mullvad/windows-service-rs/blob/04c0b0c9ccd41404c92bc4e3de1e1e47e0a22ba1/CHANGELOG.md#L23)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`SessionChangeReason` should be removed from here.
</blockquote></details>

That's an error in the previous PR, but yes, you are right! Fixed

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/125#-:-Nv_xaDM2cFIusfT_pDq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
Published to crates.io and tag pushed: https://github.com/mullvad/windows-service-rs/releases/tag/v0.7.0

**Pull request merged**
