### PR TITLE
Refactor `double_nul_terminated`

### PR DESCRIPTION
**Pull request by citreae535**
1. Rename `from_vec` to `from_slice` since it takes a slice, not a `Vec`.
2. Allocate `WideString` in `from_slice` with pre-calculated capacity.
3. Add unit tests for `from_slice`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/91)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
:lgtm: but a few left overs from other PR once again.

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/91#-:-NNkcBJ4-7h8j6Q02TYl:b-qgfv4)* status: 1 of 6 files reviewed, all discussions resolved

**Comment by pronebird** [comment]
You may want to rebase your PR since we've merged #83 today which fixes a few things you had to fix in here.

**Comment by citreae535** [comment]
Discarded those clippy changes since they are disabled by default in `1.67.1`. Should be ready to merge now.

**Comment by pronebird** [comment]
Clippy failed with the following warnings:

```
warning: the borrowed expression implements the required traits
    --> src\service.rs:1805:41
     |
1805 |     let wide = WideCString::from_os_str(&escaped)?;
     |                                         ^^^^^^^^ help: change this to: `escaped`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
     = note: `#[warn(clippy::needless_borrow)]` on by default

warning: the borrowed expression implements the required traits
  --> src\double_nul_terminated.rs:24:29
   |
24 |             wide.push_slice(&[0]);
   |                             ^^^^ help: change this to: `[0]`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: the borrowed expression implements the required traits
  --> src\double_nul_terminated.rs:26:25
   |
26 |         wide.push_slice(&[0]);
   |                         ^^^^ help: change this to: `[0]`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: `windows-service` (lib) generated 3 warnings (run `cargo clippy --fix --lib -p windows-service` to apply 3 sug
gestions)
```

**Comment by citreae535** [comment]
Yeah, those 3 warnings were fixed in the discarded commit. But I accidentally turned off clippy and forgot to add them back. Just tried a spelling check extension and fixed 2 spelling errors as well.

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/91)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
