### PR TITLE
Set description of service

### PR DESCRIPTION
**Pull request by edibopp**
This is a first step towards #31

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/32)

### CODE REVIEW

**Comment by aepsil0n** [comment]
> Check if `winsvc::SERVICE_DESCRIPTIONW` is defined and just init the struct, i.e:

It is not unfortunately. I will look into winapi to see what can be done about that.

**Comment by aepsil0n** [comment]
I am adding the struct in retep998/winapi-rs#804

**Comment by pronebird** [comment]
@aepsil0n it may take a while to get your PR merged. We're waiting for another PR of ours to be merged to winapi-rs as well. Sadly we can't expedite it. Worst case I'll merge your PR into our fork and we'll carry on. But for the release, we definitely better have both PRs merged into winapi-rs.

**Comment by retep998** [comment]
That PR has been merged *and* a new version of winapi has been published.

**Comment by edibopp** [comment]
@retep998 Thanks for the heads up. I no longer work for the company that needed me to build a Windows service. So this issue dropped off my radar. In any case, I can finish this up, when I find the time. However, if someone else wants to adapt the code to the changes in winapi, feel free to take over.

**Comment by pronebird** [comment]
@edibopp thanks for all your efforts. #54 introduces the `Service.set_description()`.

**Pull request closed without merging**
